# Generated by Django 4.1.4 on 2023-02-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60, null=True)),
                ('category', models.CharField(choices=[('Electrical tasks', 'Electrical tasks'), ('Furniture assembling', 'Furniture assembling'), ('Interior stain and paint', 'Interior stain and paint'), ('Plumbing', 'Plumbing'), ('Home upgrades', 'Home upgrades'), ('Window cleaning', 'Window cleaning'), ('Smart appliance installation', 'Smart appliance installation')], max_length=80, null=True)),
                ('order', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
