# Generated by Django 4.1.4 on 2023-02-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_remove_mail_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('taken', 'Taken'), ('active', 'Active'), ('completed', 'Completed')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
