# Generated by Django 4.1.4 on 2023-02-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('taken', 'Taken'), ('active', 'Active'), ('completed', 'Completed')], max_length=20, null=True),
        ),
    ]
